[theme]
primaryColor = "#2C3E50"         # Bleu foncé Safran
backgroundColor = "#F5F7FA"
secondaryBackgroundColor = "#E8ECF0"
textColor = "#000000"
font = "sans serif"

[server]
headless = true
runOnSave = true
